import random

quotes = [
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Don't watch the clock; do what it does. Keep going.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Everything you want is on the other side of fear.",
    "Believe you can and you're halfway there.",
    "The only impossible journey is the one you never begin.",
    "Success is the sum of small efforts repeated day in and day out.",
    "Your limitation—it's only your imagination.",
    "To live is the rarest thing in the world. Most people exist, that is all. – Oscar Wilde",
    "That it will never come again is what makes life so sweet. – Emily Dickinson",
    "It is never too late to be what you might have been. – George Eliot",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. – Ralph Waldo Emerson",
    "Pain is inevitable. Suffering is optional. – Haruki Murakami",
    "All the world's a stage, and all the men and women merely players. – William Shakespeare",
    "Be kind, for everyone you meet is fighting a hard battle. – Plato",
    "Unable are the loved to die for love is immortality. – Emily Dickinson",
    "Let me live, love, and say it well in good sentences. – Sylvia Plath",
    "Don't let your happiness depend on something you may lose. – C.S. Lewis",
    "We are all broken, that's how the light gets in. – Ernest Hemingway",
    "Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well. – Voltaire",
    "Life is tough my darling, but so are you. – Stephanie Bennett Henry",
    "Self-awareness and self-love matter. Who we are is how we lead. – Brene Brown",
    "Amateurs sit and wait for inspiration, the rest of us just get up and go to work. – Stephen King",
    "Get it down. Take chances. It may be bad, but it's the only way you can do anything really good. – William Faulkner",
    "As a writer, you should not judge, you should understand. – Ernest Hemingway",
    "To produce a mighty book, you must choose a mighty theme. – Herman Melville",
    "Ideas are like rabbits. You get a couple and learn how to handle them, and pretty soon you have a dozen. – John Steinbeck",
    "Sometimes, you read a book and it fills you with this weird evangelical zeal, and you become convinced that the shattered world will never be put back together unless and until all living humans read the book. – John Green",
    "The Six Golden Rules of Writing: Read, read, read, and write, write, write. – Ernest Gaines",
    "As for ‘Write what you know,' I was regularly told this as a beginner. I think it's a very good rule and have always obeyed it. I write about imaginary countries, alien societies on other planets, dragons, wizards, the Napa Valley in 22002. I know these things. I know them better than anybody else possibly could, so it's my duty to testify about them. – Ursula K. Le Guin",
    "You should write because you love the shape of stories and sentences and the creation of different words on a page. Writing comes from reading, and reading is the finest teacher of how to write. – Annie Proulx",
    "Find out the reason that commands you to write; see whether it has spread its roots into the very depth of your heart; confess to yourself you would have to die if you were forbidden to write. – Rainer Maria Rilke",
    "The purpose of a writer is to keep civilization from destroying itself. – Albert Camus",
    "A writer never has a vacation. For a writer life consists of either writing or thinking about writing. – Eugene Ionesco",
    "Read, read, read. Read everything – trash, classics, good and bad, and see how they do it. Just like a carpenter who works as an apprentice and studies the master. Read! You'll absorb it. Then write. If it's good, you'll find out. If it's not, throw it out of the window. – William Faulkner",
    "A good writer possesses not only his own spirit but also the spirit of his friends. – Friedrich Nietzsche",
    "Your writing voice is the deepest possible reflection of who you are. The job of your voice is not to seduce or flatter or make well-shaped sentences. In your voice, your readers should be able to hear the contents of your mind, your heart, your soul. – Meg Rosoff",
    "I am not at all in a humour for writing; I must write on until I am. – Jane Austen",
    "You don't start out writing good stuff. You start out writing crap and thinking it's good stuff, and then gradually you get better at it. That's why I say one of the most valuable traits is persistence. – Octavia E. Butler",
    "You can always edit a bad page. You can't edit a blank page. – Jodi Picoult",
    "Do not hoard what seems good for a later place in the book, or for another book; give it, give it all, give it now. – Annie Dillard",
    "If there's a book that you want to read, but it hasn't been written yet, then you must write it. – Toni Morrison",
    "Tears are words that need to be written. – Paulo Coelho",
    "Hello – Adele",
    "The first draft is just you telling yourself the story. – Terry Pratchett",
    "There is no greater agony than bearing an untold story inside you. – Maya Angelou",
    "Start writing, no matter what. The water does not flow until the faucet is turned on. – Louis L’Amour",
    "You don’t write because you want to say something, you write because you have something to say. – F. Scott Fitzgerald",
    "I write to discover what I know. – Flannery O’Connor",
    "The road to hell is paved with adverbs. – Stephen King",
    "Easy reading is damn hard writing. – Nathaniel Hawthorne",
    "The scariest moment is always just before you start. – Stephen King",
    "There are three rules for writing a novel. Unfortunately, no one knows what they are. – W. Somerset Maugham",
    "Writing is an exploration. You start from nothing and learn as you go. – E. L. Doctorow",
    "Don’t tell me the moon is shining; show me the glint of light on broken glass. – Anton Chekhov",
    "A writer is someone for whom writing is more difficult than it is for other people. – Thomas Mann",
    "There is nothing to writing. All you do is sit down at a typewriter and bleed. – Ernest Hemingway",
    "You must stay drunk on writing so reality cannot destroy you. – Ray Bradbury",
    "The difference between the almost right word and the right word is really a large matter — it’s the difference between the lightning bug and the lightning. – Mark Twain",
    "One day I will find the right words, and they will be simple. – Jack Kerouac",
    "The best time for planning a book is while you’re doing the dishes. – Agatha Christie",
    "We are all apprentices in a craft where no one ever becomes a master. – Ernest Hemingway",
    "All good writing is swimming under water and holding your breath. – F. Scott Fitzgerald",
    "The most valuable of all talents is that of never using two words when one will do. – Thomas Jefferson",
    "Cut out all these exclamation points. An exclamation point is like laughing at your own joke. – F. Scott Fitzgerald",
    "I hate writing, I love having written. – Dorothy Parker",
    "You can make anything by writing. – C.S. Lewis",
    "Write drunk, edit sober. – Ernest Hemingway (attributed but debated)",
    "Substitute ‘damn’ every time you’re inclined to write ‘very;’ your editor will delete it and the writing will be just as it should be. – Mark Twain",
    "The true alchemists do not change lead into gold; they change the world into words. – William H. Gass",
    "Write what should not be forgotten. – Isabel Allende",
    "I can shake off everything as I write; my sorrows disappear, my courage is reborn. – Anne Frank",
    "No tears in the writer, no tears in the reader. No surprise in the writer, no surprise in the reader. – Robert Frost",
    "There are no laws for the novel. There never have been, nor can there ever be. – Doris Lessing",
    "You fail only if you stop writing. – Ray Bradbury",
    "A word after a word after a word is power. – Margaret Atwood",
    "What is written without effort is in general read without pleasure. – Samuel Johnson",
    "I write for the same reason I breathe — because if I didn’t, I would die. – Isaac Asimov",
    "A writer is a world trapped in a person. – Victor Hugo",
    "Don’t bend; don’t water it down; don’t try to make it logical; don’t edit your own soul according to the fashion. Rather, follow your most intense obsessions mercilessly. – Franz Kafka",
    "Writing is the only thing that, when I do it, I don’t feel I should be doing something else. – Gloria Steinem",
    "I try to create sympathy for my characters, then turn the monsters loose. – Stephen King",
    "Close the door. Write with no one looking over your shoulder. Don’t try to figure out what other people want to hear from you; figure out what you have to say. It’s the one and only thing you have to offer. – Barbara Kingsolver",
    "The writer must believe that what he is doing is the most important thing in the world. And he must hold to this illusion even when he knows it is not true. – John Steinbeck",
    "Writing a book is a horrible, exhausting struggle, like a long bout of some painful illness. One would never undertake such a thing if one were not driven on by some demon whom one can neither resist nor understand. – George Orwell",
    "I’m writing a book. I’ve got the page numbers done. – Steven Wright",
    "Half my life is an act of revision. – John Irving",
    "Good fiction’s job is to comfort the disturbed and disturb the comfortable. – David Foster Wallace",
    "The greatest part of a writer’s time is spent in reading, in order to write. A man will turn over half a library to make one book. – Samuel Johnson",
    "Art is the passion of creation. Craft is the mastery of technique.",
    "Magic isn’t what’s performed or how. It’s what happens when the viewer’s imagination engages with the material being presented.",
    "Art controls you. Craft is a tool you wield.",
    "Creativity is already a kind of sorcery; bringing something into existence out of nothing.",
    "Deep magic isn’t a spontaneous explosion of creative energy. Real power comes from deliberation, skill, and craft.",
    "The muse comes to those who are prepared and willing; magic needs focus, ability, and attention.",
    "A good novel is generally about a single episode that has a major emotional impact on a character’s life, who is presented with an impossible moral choice.",
    "It’s not the passion-fueled torrent of words that make a book, but the calculated mastery of technique and ability.",
    "You don’t create a better story by avoiding tropes. You create a non-genred story that appeals to nobody.",
    "Books that succeed almost without fail are those that have become popular, whether or not they were expected to.",
    "Art is about self-expression, while craft is about technical mastery.",
    "Magic in writing happens when preparation meets inspiration.",
    "A compelling novel focuses on a character’s impossible problem that forces them to grow.",
    "Don’t avoid genre conventions; instead, transcend them by adding originality.",
    "A book is rarely all great — greatness is supported by good enough, and that’s okay.",
    "Creating a powerful story involves understanding both the art and the craft of writing.",
    "The real magic of writing is how it changes you as a creator.",
    "The best writing is art that flows; the skill and craft contain it into an enjoyable novel.",
    "A story that matters challenges your protagonist so deeply it threatens their very identity.",
    "The craft of writing can be learned, practiced, and perfected — magic will follow.",
    "Real magic and just a trick aren’t so different; both require preparation and practice.",
    "The true power in writing comes from deliberate practice, not just spontaneous inspiration.",
    "Your story is not about your character — it’s about your character’s problem.",
    "Creativity is sorcery; writing requires both art and the disciplined practice of craft.",
    "Your greatest weapon as a writer is the ability to channel raw emotion into structured form.",
    "Great writing shares identifiable patterns you can learn to implement.",
    "Even the most powerful magic needs a container — the craft to hold it together.",
    "Great writing happens when you channel unstructured creativity into disciplined craft.",
    "Magic in storytelling is born from a combination of spontaneous inspiration and learned skill.",
    "A compelling story puts characters in situations that force them to change or confront their deepest fears.",
    "Craft is the tool that turns raw inspiration into a story that captivates readers.",
    "Writing is both an art and a science — the muse is drawn to those who are prepared.",
    "Mastery in writing means knowing when to follow and when to transcend genre conventions.",
    "A well-crafted story weaves together powerful emotion with precise technique.",
    "The real magic of storytelling lies in the balance between spontaneous creativity and deliberate craft.",
    "Craft is the study of essentials. It’s the foundation you lay before igniting your unique magic with the heat of your pen.",
    "Writing isn’t about sitting around waiting for the muse. It’s about showing up every day and doing the work until the magic shows up.",
    "To spell was to create invisible meaning through learned rearrangement of inscrutable symbols.",
    "Great writing shares identifiable patterns that you can learn to implement without stumbling through the dark.",
    "You can’t force readers to love your book. The work must stand on its own.",
    "Choose joy. Aim for value. Practice your craft.",
    "An artist is never satisfied with the details, but a craftsman makes it work and keeps getting better.",
    "The best magic shows up when you’re prepared enough to handle and contain it.",
    "The real magic of writing is how it changes you.",
    "You are the magician. I’m simply holding up the mirror to show you the reflection of the person you already are.",
    "Craft is the tool that turns inspiration into a book.",
    "Mastery in writing means balancing creativity with disciplined practice.",
    "Real power in writing comes from combining skill with deliberate practice.",
    "Writing is an initiation — into the craft, into discipline, into your own magic.",
    "Great writing is a balance of art and craft, passion and technique.",
    "The path to becoming a successful writer involves continuous learning and adapting.",
    "The muse may be magical, but the real magic is in doing the work.",
    "Your story’s magic happens when your words touch the reader’s imagination.",
    "Don’t rely on inspiration alone; prepare, practice, and the magic will follow.",
    "Writing is a journey of self-discovery as much as it is about crafting a story.",
    "The narrative comes first — the structure, the purpose, the point. The magic isn’t in the showmanship; it’s the work’s ability to affect a particular audience. Beautiful words aren’t all that important and it doesn’t matter where you put the commas. Even if you choose the prettiest words, it won’t hold up without a good story.",
    "Writing is a learnable skill! You don’t really understand what it takes to write a book until you’ve finished one, and even then you’re just a beginner. Be proud of yourself but recognize you may need a professional editor and also to finish several more books before you start producing high-quality work.",
    "Don’t get discouraged that the writing may not be that great yet. Those sentences don’t start to shine until the last few rounds of editing. Stick with the story, use the words that convey the right images and emotions, but don’t overdo it.",
    "You don’t make something hurt by using more words. You use the right words. Sometimes authors attempt to explain why and how much something hurts with a lot of description. Stay in the scene and focus on the details and feelings of this critical moment — not the thoughts it sparks.",
    "Finish the work. As you prepare to do the work, create a ritual, a routine, and transform your workspace into an altar: this will boost your productivity and create an unstoppable writing habit. The only real key to productivity is consistency. Make a promise to yourself that you will show up even if it’s just twenty minutes a day.",
    "Your first draft is not about good writing, and trying to write your first draft well will probably sabotage the process and ultimately lead to a weaker book. The solution is to write it quickly, roughly, focusing on the story — figuring out what happens. All the gaps, plot holes, and motivations, we’ll fix later.",
    "Write the rough draft quickly. Don’t edit, don’t improve the writing, don’t focus on the sentences. Just block in the conversation, setting, and action in big chunks. If you get stuck, make a note and move on. Focus on hitting a certain word count or getting through a scene a day. Then start revising in earnest. Don’t get discouraged that the writing may not be that great yet. Those sentences don’t start to shine until the last few rounds of editing.",
    "Beautiful words aren’t all that important, and it doesn’t matter where you put the commas. Even if you choose the prettiest words, it won’t hold up without a good story. The narrative comes first — the structure, the purpose, the point. The magic isn’t in the showmanship; it’s the work’s ability to affect a particular audience."
]

def get_random_quote():
    return random.choice(quotes)
